export const EduList = [
  {
    idx: 2,
    college: "Boise State University",
    where: "Boise, ID",
    degree: "B.S.",
    major: "Computer Science",
    gpa: "3.34/4.0",
    status: "졸업",
    from: "2016.01",
    to: "2018.12",
  },
  {
    idx: 1,
    college: "Santa Monica College",
    where: "Santa Monica, CA",
    degree: "A.A.",
    major: "Accounting",
    gpa: "3.54/4.0",
    status: "편입",
    from: "2015.01",
    to: "2015.12",
  },
  {
    idx: 0,
    college: "Idaho State University",
    where: "Pocatello, ID",
    degree: "B.A.",
    major: "General Business",
    gpa: "3.72/4.0",
    status: "편입",
    from: "2014.01",
    to: "2014.12",
  },
];

export const WorkList = [
  {
    idx: 2,
    company: "(주)원스인터랙티브",
    from: "2024.03",
    to: "",
    team: "개발팀",
    position: "대리",
    role: "프론트엔드 개발자",
    skills: "skillsskillsskillsskillsskillsskills",
    details: "detailsdetailsdetailsdetailsdetailsdetails",
    projects: [{}, {}],
  },
  {
    idx: 1,
    company: "(주)씨티케이",
    from: "2022.11",
    to: "2024.02",
    team: "클립 ICT팀",
    position: "사원",
    role: "프론트엔드 개발자",
    skills: "",
    details: "",
    projects: [{}, {}],
  },
  {
    idx: 0,
    company: "(주)스마트컨버전스",
    from: "2019.11",
    to: "2020.09",
    team: "R&D 연구개발팀",
    position: "연구원",
    role: "안드로이드 개발자",
    skills: "",
    details: ["", "", ""],
    projects: [{}, {}],
  },
];

export const SkillsList = [
  {
    idx: 1,
    name: "Coding Skills",
    skills: [
      {
        so: 1,
        title: "Frontend Dev",
        desc: "",
        icon: "",
      },
      {
        so: 2,
        title: "Backend Dev",
        desc: "",
        icon: "",
      },
      {
        so: 3,
        title: "Hosting & Deployments",
        desc: "",
        icon: "",
      },
      {
        so: 4,
        title: "Web Applications",
        desc: "",
        icon: "",
      },
      {
        so: 5,
        title: "API Development",
        desc: "",
        icon: "",
      },
      {
        so: 6,
        title: "Mobile Applications",
        desc: "",
        icon: "",
      },
    ],
  },
  {
    idx: 2,
    name: "Soft Skills",
    skills: [
      {
        so: 1,
        title: "Effective Communication",
        desc: "",
        icon: "",
      },
      {
        so: 2,
        title: "Smart Collaboration",
        desc: "",
        icon: "",
      },
      {
        so: 3,
        title: "Easy Adaptability",
        desc: "",
        icon: "",
      },
      {
        so: 4,
        title: "Time Management",
        desc: "",
        icon: "",
      },
      {
        so: 5,
        title: "Problem Solving",
        desc: "",
        icon: "",
      },
      {
        so: 6,
        title: "Creativity & Innovations",
        desc: "",
        icon: "",
      },
    ],
  },
];

export const CertList = [
  {
    idx: 5,
    name: "정보처리기사",
    organized: "",
    date: "예정",
  },
  {
    idx: 4,
    name: "SQL 개발자",
    organized: "한국데이터산업진흥원",
    date: "2023.12",
  },
  {
    idx: 3,
    name: "웹디자인기능사",
    organized: "한국산업인력공단",
    date: "2023.09",
  },
  {
    idx: 2,
    name: "한국사능력검정시험 3급",
    organized: "국사편찬위원해",
    date: "2020.07",
  },
  {
    idx: 1,
    name: "워드프로세서 1급",
    organized: "대한상공회의소",
    date: "2020.05",
  },
  {
    idx: 0,
    name: "2종보통운전면허",
    organized: "경찰청(운전면허시험관리단)",
    date: "2019.01",
  },
];
